name: Build and Push Docker Image
description: Build and Push Docker Image
inputs:
  context:
    description: Docker Context
    default: .
    required: true

  dockerfile:
    description: Dockerfile location
    default: Dockerfile
    required: true

  github-token:
    description: secrets.BUILD_GITHUB_TOKEN
    required: true

  image-name:
    description: Name of the published image
    required: true

runs:
  using: composite
  steps:
    - name: Login to Amazon ECR
      id: ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Docker Metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ steps.ecr.outputs.registry }}/${{ inputs.image-name }}
        tags: |
          type=ref,event=branch
          type=sha,format=long

    - name: Build Image
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          GITHUB_TOKEN=${{ inputs.github-token }}
          GITHUB_USERNAME=OrthoFi
